"NeoBundle"

"NeoBundle Settings"

set nocompatible
filetype off

if has('vim_starting')
  set runtimepath+=~/.vim/bundle/neobundle.vim
  call neobundle#begin(expand('~/.neobundle'))
endif

"NeoBundle Plugins"

NeoBundle 'Shougo/unite.vim' 

call neobundle#end()

filetype plugin indent on

"Settings"

set nocompatible
set number
set autoindent
set cindent
set noswapfile
syntax on

"Clipboard"

set clipboard=unnamed

"Search Settings"

set hlsearch
set incsearch

"Key Settings"

set backspace=indent,eol,start
