"NeoBundle"

"NeoBundle Settings"

set nocompatible
filetype off

if has('vim_starting')
  set runtimepath+=~/.vim/bundle/neobundle.vim
  call neobundle#begin(expand('~/.neobundle'))
endif

"NeoBundle Plugins"

NeoBundle 'Shougo/unite.vim' 

call neobundle#end()

filetype plugin indent on

"Settings"

set nocompatible
set number
set noswapfile
syntax on

"Encoding"

set encoding=utf-8
set fenc=utf-8
set fencs=ucs_bom,utf-8,euc-jp,iso-2022-jp,cp932

"Indent"

set autoindent
set cindent
set tabstop=2
set shiftwidth=2
set softtabstop=0
set smarttab
set expandtab
set shiftround

"Clipboard"

set clipboard=unnamed

"Search Settings"

set ignorecase
set smartcase
set wrapscan
set hlsearch
set incsearch

"Key Settings"

set backspace=indent,eol,start
