[tools]
argo = "latest"
aws-cli = "latest"
bun = "latest"
carapace = "latest"
cargo-binstall = "latest"
chezmoi = "latest"
fzf = "latest"
gh = "latest"
ghq = "latest"
go = "latest"
hadolint = "latest"
kubectl = "latest"
kubectx = "latest"
lazygit = "latest"
node = "lts"
opencode = "latest"
pnpm = "latest"
pulumi = "latest"
rg = "latest"
rust = "latest"
starship = "latest"
terraform = "latest"
usage = "latest"
uv = "latest"
zellij = "latest"
zoxide = "latest"
"aqua:atuinsh/atuin" = "latest"
"aqua:github/copilot-cli" = "latest"
"aqua:jj-vcs/jj" = "latest"
"aqua:openai/codex" = "latest"
"aqua:rossmacarthur/sheldon" = "latest"

[settings.npm]
package_manager = "pnpm"
