[tools]
argo = "latest"
aws-cli = "latest"
bun = "latest"
carapace = "latest"
cargo-binstall = "latest"
"cargo:atuin" = "latest"
"cargo:jj-cli" = "latest"
"cargo:sheldon" = "latest"
chezmoi = "latest"
fzf = "latest"
gh = "latest"
ghq = "latest"
go = "latest"
hadolint = "latest"
kubectl = "latest"
kubectx = "latest"
lazygit = "latest"
node = "lts"
"npm:@dataform/cli" = "latest"
"npm:@fission-ai/openspec" = "latest"
"npm:@google/gemini-cli" = "latest"
opencode = "latest"
pnpm = "latest"
pulumi = "latest"
rg = "latest"
rust = "latest"
starship = "latest"
terraform = "latest"
usage = "latest"
uv = "latest"
yt-dlp = "latest"
zellij = "latest"
zoxide = "latest"
"aqua:github/copilot-cli" = "latest"
"aqua:openai/codex" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]

[settings.npm]
package_manager = "pnpm"
